PROTEUM - I/O LOG FILE
Apr-15-15
V 2.1 - IM
                   
Please enter 3 numbers separated by spaces > 1
9940 32 
1092 Please enter 3 numbers separated by spaces > 1
9940 32 
1092 Please enter 3 numbers separated by spaces > 1
9940 32 
1092 Please enter 3 numbers separated by spaces > 1
9940 32 
1092 Please enter 3 numbers separated by spaces > 1
9940 32 
1092 Please enter 3 numbers separated by spaces > 1
9940 32 
1092 