PROTEUM - I/O LOG FILE
Apr-15-15
V 2.1 - IM
                   
Please enter 4 numbers separated by spaces > 1
9940 32 
4192 Please enter 4 numbers separated by spaces > -948955504 is the smallest
1
9940 32 
c0 Please enter 4 numbers separated by spaces > -482937056 is the smallest
1
9940 32 
c0 Please enter 4 numbers separated by spaces > 1
9940 32 
4192 Please enter 4 numbers separated by spaces > 1
9940 32 
4192 Please enter 4 numbers separated by spaces > 1
9940 32 
4192 